In [6]:
import os
import pandas as pd
from tqdm import tqdm

tqdm.pandas()

df = pd.read_csv(os.path.join(os.getcwd(), 'script_url_etld_cluster_1.csv'))
df.head(10)

                     s_u     c
0   googletagmanager.com  9603
1           facebook.net  2821
2  googlesyndication.com   847
3        doubleclick.net   760
4   google-analytics.com   669
5             google.com   600
6         googleapis.com   572
7               bing.com   557
8          cookielaw.org   466
9             tiktok.com   459

In [10]:
def contains_key_word(url):
    return "google" in url

df = df.dropna()
df['related_to_google'] = df['s_u'].progress_apply(contains_key_word)
df.head(10)

100%|██████████| 1782/1782 [00:00<00:00, 1747953.63it/s]

                     s_u     c  related_to_google
0   googletagmanager.com  9603               True
1           facebook.net  2821              False
2  googlesyndication.com   847               True
3        doubleclick.net   760              False
4   google-analytics.com   669               True
5             google.com   600               True
6         googleapis.com   572               True
7               bing.com   557              False
8          cookielaw.org   466              False
9             tiktok.com   459              False