In [25]:
import pandas as pd
df = pd.read_csv('fp_cookies.csv')
df.head()

     cookies     c
0    _gcl_au  5102
1        _ga  4907
2      _abck  2262
3  __smn_fid  1671
4       AMCV  1601

In [26]:
already_checked = set([
    "mbox",
    "ajs_anonymous_id",
    "locale",
    "_pctx",
    "language",
    "rxVisitor",
    "_gd_visitor",
    "_pprv",
    "form_key",
    "device_id",
    "_ga",
    "_dd_s",
    "_ym_uid",
    "dtCookie",
    "_vwo_uuid",
    "nmstat",
    "__hstc",
    "__utma",
    "___nrbic",
    "s_ecid",
    "_abck",
    "OptanonConsent",
    "AWSALB",
    "PHPSESSID",
    "__eoi",
    "utag_main",
    "ai_user",
    "__gfp_64b",
    "mutiny.user.token",
    "consentUUID"])

first_50 = df.head(50)
remaining = df.drop(index=first_50.index)
random_25 = remaining.sample(n=25, random_state=42)
result = pd.concat([first_50, random_25])
result.head()

     cookies     c
0    _gcl_au  5102
1        _ga  4907
2      _abck  2262
3  __smn_fid  1671
4       AMCV  1601

In [27]:
names = set(df['cookies'].tolist())
print(already_checked.difference(names))

set()

In [28]:
result

              cookies     c
0             _gcl_au  5102
1                 _ga  4907
2               _abck  2262
3           __smn_fid  1671
4                AMCV  1601
...               ...   ...
1496    mba_sessionid     3
2157  _pk_id.249.3401     1
3182  _pk_id.118.d048     1
1394         vidal_fr     4
1921   _pk_id.16.ff96     2

[75 rows x 2 columns]

In [40]:
import random
import pandas as pd

df_a = pd.read_csv("cookies_05052026_name_cleaned.csv")

# Falls first_party_cookie echte Booleans enthält
df_tp = df_a[df_a["first_party_cookie"] == False]

names_tp = set(df_tp["name_cleaned"].dropna().tolist())

# bereits vorhandene Namen ausschließen
names_tp = names_tp.difference(names)

# sicherstellen, dass genug Werte vorhanden sind
sample_size = min(25, len(names_tp))

res = random.sample(sorted(names_tp), sample_size)

res

C:\Users\boett\AppData\Local\Temp\ipykernel_48864\1584448364.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_a = pd.read_csv("cookies_05052026_name_cleaned.csv")

['rdc1747692700718',
 'oval',
 'gd1747890488716',
 '6396',
 'rdc1747324316758',
 'gd1747961054641',
 'rdc1747654458187',
 'safeframe-test-cookie_79_1',
 'sgTrackingID',
 'incap_ses_221',
 'AspNetCore.OpenIdConnect.Nonce.CfDJ8E1zEo_IqoVDgqHRM0iGPECdxU-pV_xJLbLZwhzJJ2UP_OLBzJIrQIf6t_0_N_pEmnQ',
 'rdc1747566985292',
 'promoInterstitial_DESKTOP_LISTING_INTERSTITIAL_electronique_electromenager',
 'webp',
 'deeplink',
 'idg-language',
 'rdc1747367219849',
 'rdc1747785506220',
 'd_fs',
 'gd1747873770591',
 'gd1747899105509',
 'loginState',
 'unauthenicatedArticleLimitReached',
 'continent',
 'bounceClientVisit6035v']

In [49]:
a = (list(result['cookies'].tolist()) + list(res))
len(a)

100