In [2]:
import os
import pandas as pd
from glob import glob

PATH_TO_DATA = os.path.join(os.getcwd(), '..', '..', '..', '02_Data', 'multiple_key_value_pairs', 'values')
FILES = glob(os.path.join(PATH_TO_DATA, '*.csv'))
df = pd.read_csv(FILES[0])
df.head()

                                               value
0                {%22globalKey%22:2%2C%22VISIT%22:2}
1                                {%22globalKey%22:2}
2  {%22globalKey%22:3%2C%22VISIT%22:2%2C%22PAGE%2...
3                {%22globalKey%22:3%2C%22VISIT%22:2}
4  {%22globalKey%22:4%2C%22VISIT%22:2%2C%22PAGE%2...

In [3]:
from urllib.parse import unquote
from tqdm import tqdm
tqdm.pandas()

def url_decode(cookie_value):
    try:
        return unquote(cookie_value)
    except:
        return ""

df['unquote'] = df['value'].progress_apply(url_decode)
df.head()

100%|██████████| 42787/42787 [00:00<00:00, 342548.20it/s]

,value,unquote
0,{%22globalKey%22:2%2C%22VISIT%22:2},"{""globalKey"":2,""VISIT"":2}"
1,{%22globalKey%22:2},"{""globalKey"":2}"
2,{%22globalKey%22:3%2C%22VISIT%22:2%2C%22PAGE%2...,"{""globalKey"":3,""VISIT"":2,""PAGE"":2}"
3,{%22globalKey%22:3%2C%22VISIT%22:2},"{""globalKey"":3,""VISIT"":2}"
4,{%22globalKey%22:4%2C%22VISIT%22:2%2C%22PAGE%2...,"{""globalKey"":4,""VISIT"":2,""PAGE"":2,""CUSTOM"":2}"

In [10]:
def is_decoded(row):
    return row['unquote'] != row['value']

df['is_decoded'] = df.apply(is_decoded, axis=1)
df.head()

,value,unquote,is_decoded
0,{%22globalKey%22:2%2C%22VISIT%22:2},"{""globalKey"":2,""VISIT"":2}",True
1,{%22globalKey%22:2},"{""globalKey"":2}",True
2,{%22globalKey%22:3%2C%22VISIT%22:2%2C%22PAGE%2...,"{""globalKey"":3,""VISIT"":2,""PAGE"":2}",True
3,{%22globalKey%22:3%2C%22VISIT%22:2},"{""globalKey"":3,""VISIT"":2}",True
4,{%22globalKey%22:4%2C%22VISIT%22:2%2C%22PAGE%2...,"{""globalKey"":4,""VISIT"":2,""PAGE"":2,""CUSTOM"":2}",True

In [15]:
print("Multiple_Key_Value_Pairs.1.0")
df['is_decoded'].value_counts()

Multiple_Key_Value_Pairs.1.0

is_decoded
True     23518
False    19269
Name: count, dtype: int64

In [16]:
df

,value,unquote,is_decoded
0,{%22globalKey%22:2%2C%22VISIT%22:2},"{""globalKey"":2,""VISIT"":2}",True
1,{%22globalKey%22:2},"{""globalKey"":2}",True
2,{%22globalKey%22:3%2C%22VISIT%22:2%2C%22PAGE%2...,"{""globalKey"":3,""VISIT"":2,""PAGE"":2}",True
3,{%22globalKey%22:3%2C%22VISIT%22:2},"{""globalKey"":3,""VISIT"":2}",True
4,{%22globalKey%22:4%2C%22VISIT%22:2%2C%22PAGE%2...,"{""globalKey"":4,""VISIT"":2,""PAGE"":2,""CUSTOM"":2}",True
...,...,...,...
42782,{%22first_touch_timestamp%22:1747383244143%2C%...,"{""first_touch_timestamp"":1747383244143,""last_t...",True
42783,{%22first_touch_timestamp%22:1747417588271%2C%...,"{""first_touch_timestamp"":1747417588271,""last_t...",True
42784,{%22first_touch_timestamp%22:1747418364122%2C%...,"{""first_touch_timestamp"":1747418364122,""last_t...",True
42785,"{""schemaVersion"":4,""content"":{""brand"":1,""conse...","{""schemaVersion"":4,""content"":{""brand"":1,""conse...",False
42786,"{""schemaVersion"":4,""content"":{""brand"":1,""conse...","{""schemaVersion"":4,""content"":{""brand"":1,""conse...",False